//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.27 at 04:06:37 PM EDT 
//


package us.gov.ic.cvenum.ism.poctype;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CVEnumISMPocTypeValues.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CVEnumISMPocTypeValues"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token"&gt;
 *     &lt;enumeration value="ICD-710"/&gt;
 *     &lt;enumeration value="DoD-Dist-B"/&gt;
 *     &lt;enumeration value="DoD-Dist-C"/&gt;
 *     &lt;enumeration value="DoD-Dist-D"/&gt;
 *     &lt;enumeration value="DoD-Dist-E"/&gt;
 *     &lt;enumeration value="DoD-Dist-F"/&gt;
 *     &lt;enumeration value="DoD-Dist-X"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "CVEnumISMPocTypeValues", namespace = "urn:us:gov:ic:cvenum:ism:pocType")
@XmlEnum
public enum CVEnumISMPocTypeValues {


    /**
     * (U) Point-of-contact for an ICD-710 notice.
     * 
     */
    @XmlEnumValue("ICD-710")
    ICD_710("ICD-710"),

    /**
     * (U) DoD Distribution statement B from DoD Directive 5230.24
     * 
     */
    @XmlEnumValue("DoD-Dist-B")
    DO_D_DIST_B("DoD-Dist-B"),

    /**
     * (U) DoD Distribution statement C from DoD Directive 5230.24
     * 
     */
    @XmlEnumValue("DoD-Dist-C")
    DO_D_DIST_C("DoD-Dist-C"),

    /**
     * (U) DoD Distribution statement D from DoD Directive 5230.24
     * 
     */
    @XmlEnumValue("DoD-Dist-D")
    DO_D_DIST_D("DoD-Dist-D"),

    /**
     * (U) DoD Distribution statement E from DoD Directive 5230.24
     * 
     */
    @XmlEnumValue("DoD-Dist-E")
    DO_D_DIST_E("DoD-Dist-E"),

    /**
     * (U) DoD Distribution statement F from DoD Directive 5230.24
     * 
     */
    @XmlEnumValue("DoD-Dist-F")
    DO_D_DIST_F("DoD-Dist-F"),

    /**
     * (U) DoD Distribution statement X from DoD Directive 5230.24
     * 
     */
    @XmlEnumValue("DoD-Dist-X")
    DO_D_DIST_X("DoD-Dist-X");
    private final String value;

    CVEnumISMPocTypeValues(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CVEnumISMPocTypeValues fromValue(String v) {
        for (CVEnumISMPocTypeValues c: CVEnumISMPocTypeValues.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
