//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.27 at 04:06:37 PM EDT 
//


package mil.ces.metadata.mdr.ns.gsip.tspi._2_0.core;

import java.io.Serializable;
import javax.validation.constraints.NotNull;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * Cardinal Direction Type: A datatype representing the angular direction with respect to a chosen reference direction establishing 16 generalized directions (for example: southeast) based on the compass rose. [desc] The angular and reference directions are located in the horizontal plane, and the interpretation of the direction is as viewed from "above" the horizontal plane.
 * 
 * <p>Java class for CardinalDirectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CardinalDirectionType"&gt;
 *   &lt;simpleContent&gt;
 *     &lt;extension base="&lt;http://metadata.ces.mil/mdr/ns/GSIP/tspi/2.0/core&gt;CompassDirectionType"&gt;
 *       &lt;attribute name="referenceDatum" use="required" type="{http://metadata.ces.mil/mdr/ns/GSIP/tspi/2.0/core}DirectionDatumType" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/simpleContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CardinalDirectionType", propOrder = {
    "value"
})
public class CardinalDirectionType implements Serializable, Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    private final static long serialVersionUID = 1L;
    @XmlValue
    protected CompassDirectionType value;
    @XmlAttribute(name = "referenceDatum", required = true)
    @NotNull(message = "CardinalDirectionType.referenceDatum {javax.validation.constraints.NotNull.message}")
    protected DirectionDatumType referenceDatum;

    /**
     * Compass Direction Type: The 16 generalized directions (for example: southeast) based on the compass rose.
     * 
     * @return
     *     possible object is
     *     {@link CompassDirectionType }
     *     
     */
    public CompassDirectionType getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link CompassDirectionType }
     *     
     */
    public void setValue(CompassDirectionType value) {
        this.value = value;
    }

    public boolean isSetValue() {
        return (this.value!= null);
    }

    /**
     * Gets the value of the referenceDatum property.
     * 
     * @return
     *     possible object is
     *     {@link DirectionDatumType }
     *     
     */
    public DirectionDatumType getReferenceDatum() {
        return referenceDatum;
    }

    /**
     * Sets the value of the referenceDatum property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectionDatumType }
     *     
     */
    public void setReferenceDatum(DirectionDatumType value) {
        this.referenceDatum = value;
    }

    public boolean isSetReferenceDatum() {
        return (this.referenceDatum!= null);
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            CompassDirectionType theValue;
            theValue = this.getValue();
            strategy.appendField(locator, this, "value", buffer, theValue, this.isSetValue());
        }
        {
            DirectionDatumType theReferenceDatum;
            theReferenceDatum = this.getReferenceDatum();
            strategy.appendField(locator, this, "referenceDatum", buffer, theReferenceDatum, this.isSetReferenceDatum());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final CardinalDirectionType that = ((CardinalDirectionType) object);
        {
            CompassDirectionType lhsValue;
            lhsValue = this.getValue();
            CompassDirectionType rhsValue;
            rhsValue = that.getValue();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "value", lhsValue), LocatorUtils.property(thatLocator, "value", rhsValue), lhsValue, rhsValue, this.isSetValue(), that.isSetValue())) {
                return false;
            }
        }
        {
            DirectionDatumType lhsReferenceDatum;
            lhsReferenceDatum = this.getReferenceDatum();
            DirectionDatumType rhsReferenceDatum;
            rhsReferenceDatum = that.getReferenceDatum();
            if (!strategy.equals(LocatorUtils.property(thisLocator, "referenceDatum", lhsReferenceDatum), LocatorUtils.property(thatLocator, "referenceDatum", rhsReferenceDatum), lhsReferenceDatum, rhsReferenceDatum, this.isSetReferenceDatum(), that.isSetReferenceDatum())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            CompassDirectionType theValue;
            theValue = this.getValue();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "value", theValue), currentHashCode, theValue, this.isSetValue());
        }
        {
            DirectionDatumType theReferenceDatum;
            theReferenceDatum = this.getReferenceDatum();
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "referenceDatum", theReferenceDatum), currentHashCode, theReferenceDatum, this.isSetReferenceDatum());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof CardinalDirectionType) {
            final CardinalDirectionType copy = ((CardinalDirectionType) draftCopy);
            {
                Boolean valueShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetValue());
                if (valueShouldBeCopiedAndSet == Boolean.TRUE) {
                    CompassDirectionType sourceValue;
                    sourceValue = this.getValue();
                    CompassDirectionType copyValue = ((CompassDirectionType) strategy.copy(LocatorUtils.property(locator, "value", sourceValue), sourceValue, this.isSetValue()));
                    copy.setValue(copyValue);
                } else {
                    if (valueShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.value = null;
                    }
                }
            }
            {
                Boolean referenceDatumShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetReferenceDatum());
                if (referenceDatumShouldBeCopiedAndSet == Boolean.TRUE) {
                    DirectionDatumType sourceReferenceDatum;
                    sourceReferenceDatum = this.getReferenceDatum();
                    DirectionDatumType copyReferenceDatum = ((DirectionDatumType) strategy.copy(LocatorUtils.property(locator, "referenceDatum", sourceReferenceDatum), sourceReferenceDatum, this.isSetReferenceDatum()));
                    copy.setReferenceDatum(copyReferenceDatum);
                } else {
                    if (referenceDatumShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.referenceDatum = null;
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new CardinalDirectionType();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        if (right instanceof CardinalDirectionType) {
            final CardinalDirectionType target = this;
            final CardinalDirectionType leftObject = ((CardinalDirectionType) left);
            final CardinalDirectionType rightObject = ((CardinalDirectionType) right);
            {
                Boolean valueShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetValue(), rightObject.isSetValue());
                if (valueShouldBeMergedAndSet == Boolean.TRUE) {
                    CompassDirectionType lhsValue;
                    lhsValue = leftObject.getValue();
                    CompassDirectionType rhsValue;
                    rhsValue = rightObject.getValue();
                    CompassDirectionType mergedValue = ((CompassDirectionType) strategy.merge(LocatorUtils.property(leftLocator, "value", lhsValue), LocatorUtils.property(rightLocator, "value", rhsValue), lhsValue, rhsValue, leftObject.isSetValue(), rightObject.isSetValue()));
                    target.setValue(mergedValue);
                } else {
                    if (valueShouldBeMergedAndSet == Boolean.FALSE) {
                        target.value = null;
                    }
                }
            }
            {
                Boolean referenceDatumShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetReferenceDatum(), rightObject.isSetReferenceDatum());
                if (referenceDatumShouldBeMergedAndSet == Boolean.TRUE) {
                    DirectionDatumType lhsReferenceDatum;
                    lhsReferenceDatum = leftObject.getReferenceDatum();
                    DirectionDatumType rhsReferenceDatum;
                    rhsReferenceDatum = rightObject.getReferenceDatum();
                    DirectionDatumType mergedReferenceDatum = ((DirectionDatumType) strategy.merge(LocatorUtils.property(leftLocator, "referenceDatum", lhsReferenceDatum), LocatorUtils.property(rightLocator, "referenceDatum", rhsReferenceDatum), lhsReferenceDatum, rhsReferenceDatum, leftObject.isSetReferenceDatum(), rightObject.isSetReferenceDatum()));
                    target.setReferenceDatum(mergedReferenceDatum);
                } else {
                    if (referenceDatumShouldBeMergedAndSet == Boolean.FALSE) {
                        target.referenceDatum = null;
                    }
                }
            }
        }
    }

}
