//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.27 at 04:06:37 PM EDT 
//


package mil.ces.metadata.mdr.ns.gsip.tspi._2_0.core;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the mil.ces.metadata.mdr.ns.gsip.tspi._2_0.core package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: mil.ces.metadata.mdr.ns.gsip.tspi._2_0.core
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link NumericBitPresentationType }
     * 
     */
    public NumericBitPresentationType createNumericBitPresentationType() {
        return new NumericBitPresentationType();
    }

    /**
     * Create an instance of {@link QuadranglePresentationType }
     * 
     */
    public QuadranglePresentationType createQuadranglePresentationType() {
        return new QuadranglePresentationType();
    }

    /**
     * Create an instance of {@link QuadranglePresentationType.SubZoneFraction }
     * 
     */
    public QuadranglePresentationType.SubZoneFraction createQuadranglePresentationTypeSubZoneFraction() {
        return new QuadranglePresentationType.SubZoneFraction();
    }

    /**
     * Create an instance of {@link ZoneMetrePresentationType }
     * 
     */
    public ZoneMetrePresentationType createZoneMetrePresentationType() {
        return new ZoneMetrePresentationType();
    }

    /**
     * Create an instance of {@link GridMetrePresentationType }
     * 
     */
    public GridMetrePresentationType createGridMetrePresentationType() {
        return new GridMetrePresentationType();
    }

    /**
     * Create an instance of {@link GridMetrePresentationType.RelativeLocation }
     * 
     */
    public GridMetrePresentationType.RelativeLocation createGridMetrePresentationTypeRelativeLocation() {
        return new GridMetrePresentationType.RelativeLocation();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType }
     * 
     */
    public SexagesimalPresentationType createSexagesimalPresentationType() {
        return new SexagesimalPresentationType();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoSecondFraction }
     * 
     */
    public SexagesimalPresentationType.GeoSecondFraction createSexagesimalPresentationTypeGeoSecondFraction() {
        return new SexagesimalPresentationType.GeoSecondFraction();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoMinuteFraction }
     * 
     */
    public SexagesimalPresentationType.GeoMinuteFraction createSexagesimalPresentationTypeGeoMinuteFraction() {
        return new SexagesimalPresentationType.GeoMinuteFraction();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoDegreeFraction }
     * 
     */
    public SexagesimalPresentationType.GeoDegreeFraction createSexagesimalPresentationTypeGeoDegreeFraction() {
        return new SexagesimalPresentationType.GeoDegreeFraction();
    }

    /**
     * Create an instance of {@link EnvelopeType }
     * 
     */
    public EnvelopeType createEnvelopeType() {
        return new EnvelopeType();
    }

    /**
     * Create an instance of {@link PointType }
     * 
     */
    public PointType createPointType() {
        return new PointType();
    }

    /**
     * Create an instance of {@link LineStringType }
     * 
     */
    public LineStringType createLineStringType() {
        return new LineStringType();
    }

    /**
     * Create an instance of {@link CircleType }
     * 
     */
    public CircleType createCircleType() {
        return new CircleType();
    }

    /**
     * Create an instance of {@link EllipseType }
     * 
     */
    public EllipseType createEllipseType() {
        return new EllipseType();
    }

    /**
     * Create an instance of {@link PolygonType }
     * 
     */
    public PolygonType createPolygonType() {
        return new PolygonType();
    }

    /**
     * Create an instance of {@link SimplePolygonType }
     * 
     */
    public SimplePolygonType createSimplePolygonType() {
        return new SimplePolygonType();
    }

    /**
     * Create an instance of {@link SimpleRectangleType }
     * 
     */
    public SimpleRectangleType createSimpleRectangleType() {
        return new SimpleRectangleType();
    }

    /**
     * Create an instance of {@link CircularSurfaceType }
     * 
     */
    public CircularSurfaceType createCircularSurfaceType() {
        return new CircularSurfaceType();
    }

    /**
     * Create an instance of {@link EllipticalSurfaceType }
     * 
     */
    public EllipticalSurfaceType createEllipticalSurfaceType() {
        return new EllipticalSurfaceType();
    }

    /**
     * Create an instance of {@link AccelerationType }
     * 
     */
    public AccelerationType createAccelerationType() {
        return new AccelerationType();
    }

    /**
     * Create an instance of {@link AmountOfSubstanceType }
     * 
     */
    public AmountOfSubstanceType createAmountOfSubstanceType() {
        return new AmountOfSubstanceType();
    }

    /**
     * Create an instance of {@link AreaType }
     * 
     */
    public AreaType createAreaType() {
        return new AreaType();
    }

    /**
     * Create an instance of {@link CapacitanceType }
     * 
     */
    public CapacitanceType createCapacitanceType() {
        return new CapacitanceType();
    }

    /**
     * Create an instance of {@link ElectricChargeType }
     * 
     */
    public ElectricChargeType createElectricChargeType() {
        return new ElectricChargeType();
    }

    /**
     * Create an instance of {@link ElectricConductanceType }
     * 
     */
    public ElectricConductanceType createElectricConductanceType() {
        return new ElectricConductanceType();
    }

    /**
     * Create an instance of {@link ElectricCurrentType }
     * 
     */
    public ElectricCurrentType createElectricCurrentType() {
        return new ElectricCurrentType();
    }

    /**
     * Create an instance of {@link ElectricResistanceType }
     * 
     */
    public ElectricResistanceType createElectricResistanceType() {
        return new ElectricResistanceType();
    }

    /**
     * Create an instance of {@link ElectromotiveForceType }
     * 
     */
    public ElectromotiveForceType createElectromotiveForceType() {
        return new ElectromotiveForceType();
    }

    /**
     * Create an instance of {@link EnergyType }
     * 
     */
    public EnergyType createEnergyType() {
        return new EnergyType();
    }

    /**
     * Create an instance of {@link ForceType }
     * 
     */
    public ForceType createForceType() {
        return new ForceType();
    }

    /**
     * Create an instance of {@link FrequencyType }
     * 
     */
    public FrequencyType createFrequencyType() {
        return new FrequencyType();
    }

    /**
     * Create an instance of {@link GeopotentialEnergyLengthType }
     * 
     */
    public GeopotentialEnergyLengthType createGeopotentialEnergyLengthType() {
        return new GeopotentialEnergyLengthType();
    }

    /**
     * Create an instance of {@link IlluminanceType }
     * 
     */
    public IlluminanceType createIlluminanceType() {
        return new IlluminanceType();
    }

    /**
     * Create an instance of {@link InductanceType }
     * 
     */
    public InductanceType createInductanceType() {
        return new InductanceType();
    }

    /**
     * Create an instance of {@link IrradianceType }
     * 
     */
    public IrradianceType createIrradianceType() {
        return new IrradianceType();
    }

    /**
     * Create an instance of {@link LengthType }
     * 
     */
    public LengthType createLengthType() {
        return new LengthType();
    }

    /**
     * Create an instance of {@link LinearDensityType }
     * 
     */
    public LinearDensityType createLinearDensityType() {
        return new LinearDensityType();
    }

    /**
     * Create an instance of {@link LinearEnergyTransferType }
     * 
     */
    public LinearEnergyTransferType createLinearEnergyTransferType() {
        return new LinearEnergyTransferType();
    }

    /**
     * Create an instance of {@link LuminousFluxType }
     * 
     */
    public LuminousFluxType createLuminousFluxType() {
        return new LuminousFluxType();
    }

    /**
     * Create an instance of {@link LuminousIntensityType }
     * 
     */
    public LuminousIntensityType createLuminousIntensityType() {
        return new LuminousIntensityType();
    }

    /**
     * Create an instance of {@link MagneticFluxType }
     * 
     */
    public MagneticFluxType createMagneticFluxType() {
        return new MagneticFluxType();
    }

    /**
     * Create an instance of {@link MagneticFluxDensityType }
     * 
     */
    public MagneticFluxDensityType createMagneticFluxDensityType() {
        return new MagneticFluxDensityType();
    }

    /**
     * Create an instance of {@link MagneticFluxDensityGradientType }
     * 
     */
    public MagneticFluxDensityGradientType createMagneticFluxDensityGradientType() {
        return new MagneticFluxDensityGradientType();
    }

    /**
     * Create an instance of {@link MassType }
     * 
     */
    public MassType createMassType() {
        return new MassType();
    }

    /**
     * Create an instance of {@link MassDensityType }
     * 
     */
    public MassDensityType createMassDensityType() {
        return new MassDensityType();
    }

    /**
     * Create an instance of {@link MassFractionType }
     * 
     */
    public MassFractionType createMassFractionType() {
        return new MassFractionType();
    }

    /**
     * Create an instance of {@link MassRateType }
     * 
     */
    public MassRateType createMassRateType() {
        return new MassRateType();
    }

    /**
     * Create an instance of {@link NoncomparableUnitType }
     * 
     */
    public NoncomparableUnitType createNoncomparableUnitType() {
        return new NoncomparableUnitType();
    }

    /**
     * Create an instance of {@link PlaneAngleType }
     * 
     */
    public PlaneAngleType createPlaneAngleType() {
        return new PlaneAngleType();
    }

    /**
     * Create an instance of {@link PowerType }
     * 
     */
    public PowerType createPowerType() {
        return new PowerType();
    }

    /**
     * Create an instance of {@link PowerLevelDifferenceType }
     * 
     */
    public PowerLevelDifferenceType createPowerLevelDifferenceType() {
        return new PowerLevelDifferenceType();
    }

    /**
     * Create an instance of {@link PowerLevelDiffLenGradientType }
     * 
     */
    public PowerLevelDiffLenGradientType createPowerLevelDiffLenGradientType() {
        return new PowerLevelDiffLenGradientType();
    }

    /**
     * Create an instance of {@link PressureType }
     * 
     */
    public PressureType createPressureType() {
        return new PressureType();
    }

    /**
     * Create an instance of {@link PureNumberType }
     * 
     */
    public PureNumberType createPureNumberType() {
        return new PureNumberType();
    }

    /**
     * Create an instance of {@link RadiationAbsorbedDoseType }
     * 
     */
    public RadiationAbsorbedDoseType createRadiationAbsorbedDoseType() {
        return new RadiationAbsorbedDoseType();
    }

    /**
     * Create an instance of {@link RadiationDoseEquivalentType }
     * 
     */
    public RadiationDoseEquivalentType createRadiationDoseEquivalentType() {
        return new RadiationDoseEquivalentType();
    }

    /**
     * Create an instance of {@link RadionuclideActivityType }
     * 
     */
    public RadionuclideActivityType createRadionuclideActivityType() {
        return new RadionuclideActivityType();
    }

    /**
     * Create an instance of {@link RateType }
     * 
     */
    public RateType createRateType() {
        return new RateType();
    }

    /**
     * Create an instance of {@link ReciprocalAreaType }
     * 
     */
    public ReciprocalAreaType createReciprocalAreaType() {
        return new ReciprocalAreaType();
    }

    /**
     * Create an instance of {@link ReciprocalTimeType }
     * 
     */
    public ReciprocalTimeType createReciprocalTimeType() {
        return new ReciprocalTimeType();
    }

    /**
     * Create an instance of {@link SolidAngleType }
     * 
     */
    public SolidAngleType createSolidAngleType() {
        return new SolidAngleType();
    }

    /**
     * Create an instance of {@link SoundSpeedRatioType }
     * 
     */
    public SoundSpeedRatioType createSoundSpeedRatioType() {
        return new SoundSpeedRatioType();
    }

    /**
     * Create an instance of {@link SpeedType }
     * 
     */
    public SpeedType createSpeedType() {
        return new SpeedType();
    }

    /**
     * Create an instance of {@link SurfaceMassDensityRateType }
     * 
     */
    public SurfaceMassDensityRateType createSurfaceMassDensityRateType() {
        return new SurfaceMassDensityRateType();
    }

    /**
     * Create an instance of {@link ThermodynamicTemperatureType }
     * 
     */
    public ThermodynamicTemperatureType createThermodynamicTemperatureType() {
        return new ThermodynamicTemperatureType();
    }

    /**
     * Create an instance of {@link TimeType }
     * 
     */
    public TimeType createTimeType() {
        return new TimeType();
    }

    /**
     * Create an instance of {@link VolumeType }
     * 
     */
    public VolumeType createVolumeType() {
        return new VolumeType();
    }

    /**
     * Create an instance of {@link VolumeFlowRateType }
     * 
     */
    public VolumeFlowRateType createVolumeFlowRateType() {
        return new VolumeFlowRateType();
    }

    /**
     * Create an instance of {@link VolumeFractionType }
     * 
     */
    public VolumeFractionType createVolumeFractionType() {
        return new VolumeFractionType();
    }

    /**
     * Create an instance of {@link HorizontalPresentationType }
     * 
     */
    public HorizontalPresentationType createHorizontalPresentationType() {
        return new HorizontalPresentationType();
    }

    /**
     * Create an instance of {@link VerticalPresentationType }
     * 
     */
    public VerticalPresentationType createVerticalPresentationType() {
        return new VerticalPresentationType();
    }

    /**
     * Create an instance of {@link HorizontalResolutionType }
     * 
     */
    public HorizontalResolutionType createHorizontalResolutionType() {
        return new HorizontalResolutionType();
    }

    /**
     * Create an instance of {@link VerticalResolutionType }
     * 
     */
    public VerticalResolutionType createVerticalResolutionType() {
        return new VerticalResolutionType();
    }

    /**
     * Create an instance of {@link AltitudeMeasureType }
     * 
     */
    public AltitudeMeasureType createAltitudeMeasureType() {
        return new AltitudeMeasureType();
    }

    /**
     * Create an instance of {@link DepthMeasureType }
     * 
     */
    public DepthMeasureType createDepthMeasureType() {
        return new DepthMeasureType();
    }

    /**
     * Create an instance of {@link DirectionMeasureType }
     * 
     */
    public DirectionMeasureType createDirectionMeasureType() {
        return new DirectionMeasureType();
    }

    /**
     * Create an instance of {@link CardinalDirectionType }
     * 
     */
    public CardinalDirectionType createCardinalDirectionType() {
        return new CardinalDirectionType();
    }

    /**
     * Create an instance of {@link NumericBitPresentationType.Encoded20Bit }
     * 
     */
    public NumericBitPresentationType.Encoded20Bit createNumericBitPresentationTypeEncoded20Bit() {
        return new NumericBitPresentationType.Encoded20Bit();
    }

    /**
     * Create an instance of {@link NumericBitPresentationType.Encoded21Bit }
     * 
     */
    public NumericBitPresentationType.Encoded21Bit createNumericBitPresentationTypeEncoded21Bit() {
        return new NumericBitPresentationType.Encoded21Bit();
    }

    /**
     * Create an instance of {@link NumericBitPresentationType.Encoded23Bit }
     * 
     */
    public NumericBitPresentationType.Encoded23Bit createNumericBitPresentationTypeEncoded23Bit() {
        return new NumericBitPresentationType.Encoded23Bit();
    }

    /**
     * Create an instance of {@link NumericBitPresentationType.Encoded25Bit }
     * 
     */
    public NumericBitPresentationType.Encoded25Bit createNumericBitPresentationTypeEncoded25Bit() {
        return new NumericBitPresentationType.Encoded25Bit();
    }

    /**
     * Create an instance of {@link NumericBitPresentationType.Encoded31Bit }
     * 
     */
    public NumericBitPresentationType.Encoded31Bit createNumericBitPresentationTypeEncoded31Bit() {
        return new NumericBitPresentationType.Encoded31Bit();
    }

    /**
     * Create an instance of {@link QuadranglePresentationType.SubZoneMinute }
     * 
     */
    public QuadranglePresentationType.SubZoneMinute createQuadranglePresentationTypeSubZoneMinute() {
        return new QuadranglePresentationType.SubZoneMinute();
    }

    /**
     * Create an instance of {@link QuadranglePresentationType.SubZoneFraction.Deciminute }
     * 
     */
    public QuadranglePresentationType.SubZoneFraction.Deciminute createQuadranglePresentationTypeSubZoneFractionDeciminute() {
        return new QuadranglePresentationType.SubZoneFraction.Deciminute();
    }

    /**
     * Create an instance of {@link QuadranglePresentationType.SubZoneFraction.Centiminute }
     * 
     */
    public QuadranglePresentationType.SubZoneFraction.Centiminute createQuadranglePresentationTypeSubZoneFractionCentiminute() {
        return new QuadranglePresentationType.SubZoneFraction.Centiminute();
    }

    /**
     * Create an instance of {@link ZoneMetrePresentationType.MetreNorthing }
     * 
     */
    public ZoneMetrePresentationType.MetreNorthing createZoneMetrePresentationTypeMetreNorthing() {
        return new ZoneMetrePresentationType.MetreNorthing();
    }

    /**
     * Create an instance of {@link GridMetrePresentationType.RelativeLocation.Decakilometre }
     * 
     */
    public GridMetrePresentationType.RelativeLocation.Decakilometre createGridMetrePresentationTypeRelativeLocationDecakilometre() {
        return new GridMetrePresentationType.RelativeLocation.Decakilometre();
    }

    /**
     * Create an instance of {@link GridMetrePresentationType.RelativeLocation.Kilometre }
     * 
     */
    public GridMetrePresentationType.RelativeLocation.Kilometre createGridMetrePresentationTypeRelativeLocationKilometre() {
        return new GridMetrePresentationType.RelativeLocation.Kilometre();
    }

    /**
     * Create an instance of {@link GridMetrePresentationType.RelativeLocation.Hectometre }
     * 
     */
    public GridMetrePresentationType.RelativeLocation.Hectometre createGridMetrePresentationTypeRelativeLocationHectometre() {
        return new GridMetrePresentationType.RelativeLocation.Hectometre();
    }

    /**
     * Create an instance of {@link GridMetrePresentationType.RelativeLocation.Decametre }
     * 
     */
    public GridMetrePresentationType.RelativeLocation.Decametre createGridMetrePresentationTypeRelativeLocationDecametre() {
        return new GridMetrePresentationType.RelativeLocation.Decametre();
    }

    /**
     * Create an instance of {@link GridMetrePresentationType.RelativeLocation.Metre }
     * 
     */
    public GridMetrePresentationType.RelativeLocation.Metre createGridMetrePresentationTypeRelativeLocationMetre() {
        return new GridMetrePresentationType.RelativeLocation.Metre();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoDegree }
     * 
     */
    public SexagesimalPresentationType.GeoDegree createSexagesimalPresentationTypeGeoDegree() {
        return new SexagesimalPresentationType.GeoDegree();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoMinute }
     * 
     */
    public SexagesimalPresentationType.GeoMinute createSexagesimalPresentationTypeGeoMinute() {
        return new SexagesimalPresentationType.GeoMinute();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoSecond }
     * 
     */
    public SexagesimalPresentationType.GeoSecond createSexagesimalPresentationTypeGeoSecond() {
        return new SexagesimalPresentationType.GeoSecond();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoSecondFraction.Decisecond }
     * 
     */
    public SexagesimalPresentationType.GeoSecondFraction.Decisecond createSexagesimalPresentationTypeGeoSecondFractionDecisecond() {
        return new SexagesimalPresentationType.GeoSecondFraction.Decisecond();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoSecondFraction.Centisecond }
     * 
     */
    public SexagesimalPresentationType.GeoSecondFraction.Centisecond createSexagesimalPresentationTypeGeoSecondFractionCentisecond() {
        return new SexagesimalPresentationType.GeoSecondFraction.Centisecond();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoSecondFraction.Millisecond }
     * 
     */
    public SexagesimalPresentationType.GeoSecondFraction.Millisecond createSexagesimalPresentationTypeGeoSecondFractionMillisecond() {
        return new SexagesimalPresentationType.GeoSecondFraction.Millisecond();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoMinuteFraction.Deciminute }
     * 
     */
    public SexagesimalPresentationType.GeoMinuteFraction.Deciminute createSexagesimalPresentationTypeGeoMinuteFractionDeciminute() {
        return new SexagesimalPresentationType.GeoMinuteFraction.Deciminute();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoMinuteFraction.Centiminute }
     * 
     */
    public SexagesimalPresentationType.GeoMinuteFraction.Centiminute createSexagesimalPresentationTypeGeoMinuteFractionCentiminute() {
        return new SexagesimalPresentationType.GeoMinuteFraction.Centiminute();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoMinuteFraction.Milliminute }
     * 
     */
    public SexagesimalPresentationType.GeoMinuteFraction.Milliminute createSexagesimalPresentationTypeGeoMinuteFractionMilliminute() {
        return new SexagesimalPresentationType.GeoMinuteFraction.Milliminute();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoMinuteFraction.Decimilliminute }
     * 
     */
    public SexagesimalPresentationType.GeoMinuteFraction.Decimilliminute createSexagesimalPresentationTypeGeoMinuteFractionDecimilliminute() {
        return new SexagesimalPresentationType.GeoMinuteFraction.Decimilliminute();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoDegreeFraction.Decidegree }
     * 
     */
    public SexagesimalPresentationType.GeoDegreeFraction.Decidegree createSexagesimalPresentationTypeGeoDegreeFractionDecidegree() {
        return new SexagesimalPresentationType.GeoDegreeFraction.Decidegree();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoDegreeFraction.Centidegree }
     * 
     */
    public SexagesimalPresentationType.GeoDegreeFraction.Centidegree createSexagesimalPresentationTypeGeoDegreeFractionCentidegree() {
        return new SexagesimalPresentationType.GeoDegreeFraction.Centidegree();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoDegreeFraction.Millidegree }
     * 
     */
    public SexagesimalPresentationType.GeoDegreeFraction.Millidegree createSexagesimalPresentationTypeGeoDegreeFractionMillidegree() {
        return new SexagesimalPresentationType.GeoDegreeFraction.Millidegree();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoDegreeFraction.Decimillidegree }
     * 
     */
    public SexagesimalPresentationType.GeoDegreeFraction.Decimillidegree createSexagesimalPresentationTypeGeoDegreeFractionDecimillidegree() {
        return new SexagesimalPresentationType.GeoDegreeFraction.Decimillidegree();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoDegreeFraction.Centimillidegree }
     * 
     */
    public SexagesimalPresentationType.GeoDegreeFraction.Centimillidegree createSexagesimalPresentationTypeGeoDegreeFractionCentimillidegree() {
        return new SexagesimalPresentationType.GeoDegreeFraction.Centimillidegree();
    }

    /**
     * Create an instance of {@link SexagesimalPresentationType.GeoDegreeFraction.Microdegree }
     * 
     */
    public SexagesimalPresentationType.GeoDegreeFraction.Microdegree createSexagesimalPresentationTypeGeoDegreeFractionMicrodegree() {
        return new SexagesimalPresentationType.GeoDegreeFraction.Microdegree();
    }

    /**
     * Create an instance of {@link EnvelopeType.LowerCorner }
     * 
     */
    public EnvelopeType.LowerCorner createEnvelopeTypeLowerCorner() {
        return new EnvelopeType.LowerCorner();
    }

    /**
     * Create an instance of {@link EnvelopeType.UpperCorner }
     * 
     */
    public EnvelopeType.UpperCorner createEnvelopeTypeUpperCorner() {
        return new EnvelopeType.UpperCorner();
    }

    /**
     * Create an instance of {@link EnvelopeType.HorizPresentation }
     * 
     */
    public EnvelopeType.HorizPresentation createEnvelopeTypeHorizPresentation() {
        return new EnvelopeType.HorizPresentation();
    }

    /**
     * Create an instance of {@link EnvelopeType.VertPresentation }
     * 
     */
    public EnvelopeType.VertPresentation createEnvelopeTypeVertPresentation() {
        return new EnvelopeType.VertPresentation();
    }

}
