//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.27 at 04:06:37 PM EDT 
//


package us.mil.ces.metadata.ddms._5;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import org.jvnet.jaxb2_commons.lang.CopyStrategy2;
import org.jvnet.jaxb2_commons.lang.CopyTo2;
import org.jvnet.jaxb2_commons.lang.Equals2;
import org.jvnet.jaxb2_commons.lang.EqualsStrategy2;
import org.jvnet.jaxb2_commons.lang.HashCode2;
import org.jvnet.jaxb2_commons.lang.HashCodeStrategy2;
import org.jvnet.jaxb2_commons.lang.JAXBCopyStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBEqualsStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBHashCodeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBMergeStrategy;
import org.jvnet.jaxb2_commons.lang.JAXBToStringStrategy;
import org.jvnet.jaxb2_commons.lang.MergeFrom2;
import org.jvnet.jaxb2_commons.lang.MergeStrategy2;
import org.jvnet.jaxb2_commons.lang.ToString2;
import org.jvnet.jaxb2_commons.lang.ToStringStrategy2;
import org.jvnet.jaxb2_commons.locator.ObjectLocator;
import org.jvnet.jaxb2_commons.locator.util.LocatorUtils;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;choice maxOccurs="unbounded"&gt;
 *         &lt;element name="name" type="{urn:us:mil:ces:metadata:ddms:5}simpleTokenType"/&gt;
 *         &lt;element name="region" type="{urn:us:mil:ces:metadata:ddms:5}simpleTokenType"/&gt;
 *         &lt;element ref="{urn:us:mil:ces:metadata:ddms:5}countryCode"/&gt;
 *         &lt;element ref="{urn:us:mil:ces:metadata:ddms:5}subDivisionCode"/&gt;
 *         &lt;element ref="{urn:us:mil:ces:metadata:ddms:5}facilityIdentifier"/&gt;
 *       &lt;/choice&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "nameOrRegionOrCountryCode"
})
@XmlRootElement(name = "geographicIdentifier")
public class GeographicIdentifier implements Serializable, Cloneable, CopyTo2, Equals2, HashCode2, MergeFrom2, ToString2
{

    private final static long serialVersionUID = 1L;
    @XmlElementRefs({
        @XmlElementRef(name = "region", namespace = "urn:us:mil:ces:metadata:ddms:5", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "name", namespace = "urn:us:mil:ces:metadata:ddms:5", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "countryCode", namespace = "urn:us:mil:ces:metadata:ddms:5", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "subDivisionCode", namespace = "urn:us:mil:ces:metadata:ddms:5", type = JAXBElement.class, required = false),
        @XmlElementRef(name = "facilityIdentifier", namespace = "urn:us:mil:ces:metadata:ddms:5", type = JAXBElement.class, required = false)
    })
    protected List<JAXBElement<? extends Serializable>> nameOrRegionOrCountryCode;

    /**
     * Gets the value of the nameOrRegionOrCountryCode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nameOrRegionOrCountryCode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNameOrRegionOrCountryCode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link CompoundCountryCodeIdentifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link CompoundCountryCodeIdentifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link FacilityIdentifierType }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<JAXBElement<? extends Serializable>> getNameOrRegionOrCountryCode() {
        if (nameOrRegionOrCountryCode == null) {
            nameOrRegionOrCountryCode = new ArrayList<JAXBElement<? extends Serializable>>();
        }
        return this.nameOrRegionOrCountryCode;
    }

    public boolean isSetNameOrRegionOrCountryCode() {
        return ((this.nameOrRegionOrCountryCode!= null)&&(!this.nameOrRegionOrCountryCode.isEmpty()));
    }

    public void unsetNameOrRegionOrCountryCode() {
        this.nameOrRegionOrCountryCode = null;
    }

    public String toString() {
        final ToStringStrategy2 strategy = JAXBToStringStrategy.INSTANCE;
        final StringBuilder buffer = new StringBuilder();
        append(null, buffer, strategy);
        return buffer.toString();
    }

    public StringBuilder append(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        strategy.appendStart(locator, this, buffer);
        appendFields(locator, buffer, strategy);
        strategy.appendEnd(locator, this, buffer);
        return buffer;
    }

    public StringBuilder appendFields(ObjectLocator locator, StringBuilder buffer, ToStringStrategy2 strategy) {
        {
            List<JAXBElement<? extends Serializable>> theNameOrRegionOrCountryCode;
            theNameOrRegionOrCountryCode = (this.isSetNameOrRegionOrCountryCode()?this.getNameOrRegionOrCountryCode():null);
            strategy.appendField(locator, this, "nameOrRegionOrCountryCode", buffer, theNameOrRegionOrCountryCode, this.isSetNameOrRegionOrCountryCode());
        }
        return buffer;
    }

    public boolean equals(ObjectLocator thisLocator, ObjectLocator thatLocator, Object object, EqualsStrategy2 strategy) {
        if ((object == null)||(this.getClass()!= object.getClass())) {
            return false;
        }
        if (this == object) {
            return true;
        }
        final GeographicIdentifier that = ((GeographicIdentifier) object);
        {
            List<JAXBElement<? extends Serializable>> lhsNameOrRegionOrCountryCode;
            lhsNameOrRegionOrCountryCode = (this.isSetNameOrRegionOrCountryCode()?this.getNameOrRegionOrCountryCode():null);
            List<JAXBElement<? extends Serializable>> rhsNameOrRegionOrCountryCode;
            rhsNameOrRegionOrCountryCode = (that.isSetNameOrRegionOrCountryCode()?that.getNameOrRegionOrCountryCode():null);
            if (!strategy.equals(LocatorUtils.property(thisLocator, "nameOrRegionOrCountryCode", lhsNameOrRegionOrCountryCode), LocatorUtils.property(thatLocator, "nameOrRegionOrCountryCode", rhsNameOrRegionOrCountryCode), lhsNameOrRegionOrCountryCode, rhsNameOrRegionOrCountryCode, this.isSetNameOrRegionOrCountryCode(), that.isSetNameOrRegionOrCountryCode())) {
                return false;
            }
        }
        return true;
    }

    public boolean equals(Object object) {
        final EqualsStrategy2 strategy = JAXBEqualsStrategy.INSTANCE;
        return equals(null, null, object, strategy);
    }

    public int hashCode(ObjectLocator locator, HashCodeStrategy2 strategy) {
        int currentHashCode = 1;
        {
            List<JAXBElement<? extends Serializable>> theNameOrRegionOrCountryCode;
            theNameOrRegionOrCountryCode = (this.isSetNameOrRegionOrCountryCode()?this.getNameOrRegionOrCountryCode():null);
            currentHashCode = strategy.hashCode(LocatorUtils.property(locator, "nameOrRegionOrCountryCode", theNameOrRegionOrCountryCode), currentHashCode, theNameOrRegionOrCountryCode, this.isSetNameOrRegionOrCountryCode());
        }
        return currentHashCode;
    }

    public int hashCode() {
        final HashCodeStrategy2 strategy = JAXBHashCodeStrategy.INSTANCE;
        return this.hashCode(null, strategy);
    }

    public Object clone() {
        return copyTo(createNewInstance());
    }

    public Object copyTo(Object target) {
        final CopyStrategy2 strategy = JAXBCopyStrategy.INSTANCE;
        return copyTo(null, target, strategy);
    }

    public Object copyTo(ObjectLocator locator, Object target, CopyStrategy2 strategy) {
        final Object draftCopy = ((target == null)?createNewInstance():target);
        if (draftCopy instanceof GeographicIdentifier) {
            final GeographicIdentifier copy = ((GeographicIdentifier) draftCopy);
            {
                Boolean nameOrRegionOrCountryCodeShouldBeCopiedAndSet = strategy.shouldBeCopiedAndSet(locator, this.isSetNameOrRegionOrCountryCode());
                if (nameOrRegionOrCountryCodeShouldBeCopiedAndSet == Boolean.TRUE) {
                    List<JAXBElement<? extends Serializable>> sourceNameOrRegionOrCountryCode;
                    sourceNameOrRegionOrCountryCode = (this.isSetNameOrRegionOrCountryCode()?this.getNameOrRegionOrCountryCode():null);
                    @SuppressWarnings("unchecked")
                    List<JAXBElement<? extends Serializable>> copyNameOrRegionOrCountryCode = ((List<JAXBElement<? extends Serializable>> ) strategy.copy(LocatorUtils.property(locator, "nameOrRegionOrCountryCode", sourceNameOrRegionOrCountryCode), sourceNameOrRegionOrCountryCode, this.isSetNameOrRegionOrCountryCode()));
                    copy.unsetNameOrRegionOrCountryCode();
                    if (copyNameOrRegionOrCountryCode!= null) {
                        List<JAXBElement<? extends Serializable>> uniqueNameOrRegionOrCountryCodel = copy.getNameOrRegionOrCountryCode();
                        uniqueNameOrRegionOrCountryCodel.addAll(copyNameOrRegionOrCountryCode);
                    }
                } else {
                    if (nameOrRegionOrCountryCodeShouldBeCopiedAndSet == Boolean.FALSE) {
                        copy.unsetNameOrRegionOrCountryCode();
                    }
                }
            }
        }
        return draftCopy;
    }

    public Object createNewInstance() {
        return new GeographicIdentifier();
    }

    public void mergeFrom(Object left, Object right) {
        final MergeStrategy2 strategy = JAXBMergeStrategy.INSTANCE;
        mergeFrom(null, null, left, right, strategy);
    }

    public void mergeFrom(ObjectLocator leftLocator, ObjectLocator rightLocator, Object left, Object right, MergeStrategy2 strategy) {
        if (right instanceof GeographicIdentifier) {
            final GeographicIdentifier target = this;
            final GeographicIdentifier leftObject = ((GeographicIdentifier) left);
            final GeographicIdentifier rightObject = ((GeographicIdentifier) right);
            {
                Boolean nameOrRegionOrCountryCodeShouldBeMergedAndSet = strategy.shouldBeMergedAndSet(leftLocator, rightLocator, leftObject.isSetNameOrRegionOrCountryCode(), rightObject.isSetNameOrRegionOrCountryCode());
                if (nameOrRegionOrCountryCodeShouldBeMergedAndSet == Boolean.TRUE) {
                    List<JAXBElement<? extends Serializable>> lhsNameOrRegionOrCountryCode;
                    lhsNameOrRegionOrCountryCode = (leftObject.isSetNameOrRegionOrCountryCode()?leftObject.getNameOrRegionOrCountryCode():null);
                    List<JAXBElement<? extends Serializable>> rhsNameOrRegionOrCountryCode;
                    rhsNameOrRegionOrCountryCode = (rightObject.isSetNameOrRegionOrCountryCode()?rightObject.getNameOrRegionOrCountryCode():null);
                    List<JAXBElement<? extends Serializable>> mergedNameOrRegionOrCountryCode = ((List<JAXBElement<? extends Serializable>> ) strategy.merge(LocatorUtils.property(leftLocator, "nameOrRegionOrCountryCode", lhsNameOrRegionOrCountryCode), LocatorUtils.property(rightLocator, "nameOrRegionOrCountryCode", rhsNameOrRegionOrCountryCode), lhsNameOrRegionOrCountryCode, rhsNameOrRegionOrCountryCode, leftObject.isSetNameOrRegionOrCountryCode(), rightObject.isSetNameOrRegionOrCountryCode()));
                    target.unsetNameOrRegionOrCountryCode();
                    if (mergedNameOrRegionOrCountryCode!= null) {
                        List<JAXBElement<? extends Serializable>> uniqueNameOrRegionOrCountryCodel = target.getNameOrRegionOrCountryCode();
                        uniqueNameOrRegionOrCountryCodel.addAll(mergedNameOrRegionOrCountryCode);
                    }
                } else {
                    if (nameOrRegionOrCountryCodeShouldBeMergedAndSet == Boolean.FALSE) {
                        target.unsetNameOrRegionOrCountryCode();
                    }
                }
            }
        }
    }

    public void setNameOrRegionOrCountryCode(List<JAXBElement<? extends Serializable>> value) {
        this.nameOrRegionOrCountryCode = null;
        if (value!= null) {
            List<JAXBElement<? extends Serializable>> draftl = this.getNameOrRegionOrCountryCode();
            draftl.addAll(value);
        }
    }

}
