//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.07.27 at 04:06:37 PM EDT 
//


package us.mil.ces.metadata.ddms._5;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;
import javax.xml.namespace.QName;
import us.gov.ic.virt.VirtualCoverageType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the us.mil.ces.metadata.ddms._5 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Resource_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "resource");
    private final static QName _VirtualCoverage_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "virtualCoverage");
    private final static QName _GeospatialCoverage_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "geospatialCoverage");
    private final static QName _CountryCode_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "countryCode");
    private final static QName _SubDivisionCode_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "subDivisionCode");
    private final static QName _FacilityIdentifier_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "facilityIdentifier");
    private final static QName _BoundingGeometry_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "boundingGeometry");
    private final static QName _MetacardInfo_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "metacardInfo");
    private final static QName _Identifier_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "identifier");
    private final static QName _Title_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "title");
    private final static QName _Subtitle_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "subtitle");
    private final static QName _Creator_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "creator");
    private final static QName _Publisher_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "publisher");
    private final static QName _Contributor_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "contributor");
    private final static QName _PointOfContact_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "pointOfContact");
    private final static QName _Source_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "source");
    private final static QName _Language_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "language");
    private final static QName _Description_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "description");
    private final static QName _Dates_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "dates");
    private final static QName _Rights_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "rights");
    private final static QName _Type_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "type");
    private final static QName _Format_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "format");
    private final static QName _Medium_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "medium");
    private final static QName _MimeType_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "mimeType");
    private final static QName _Extent_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "extent");
    private final static QName _SubjectCoverage_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "subjectCoverage");
    private final static QName _Category_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "category");
    private final static QName _Keyword_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "keyword");
    private final static QName _ProductionMetric_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "productionMetric");
    private final static QName _NonStateActor_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "nonStateActor");
    private final static QName _TemporalCoverage_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "temporalCoverage");
    private final static QName _Organization_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "organization");
    private final static QName _Person_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "person");
    private final static QName _Service_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "service");
    private final static QName _Unknown_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "unknown");
    private final static QName _RelatedResource_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "relatedResource");
    private final static QName _ResourceManagement_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "resourceManagement");
    private final static QName _ProcessingInfo_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "processingInfo");
    private final static QName _RecordsManagementInfo_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "recordsManagementInfo");
    private final static QName _RevisionRecall_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "revisionRecall");
    private final static QName _Affiliation_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "affiliation");
    private final static QName _GeographicIdentifierName_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "name");
    private final static QName _GeographicIdentifierRegion_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "region");
    private final static QName _RevisionRecallTypeLink_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "link");
    private final static QName _RevisionRecallTypeDetails_QNAME = new QName("urn:us:mil:ces:metadata:ddms:5", "details");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: us.mil.ces.metadata.ddms._5
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TaskingInfoType }
     * 
     */
    public TaskingInfoType createTaskingInfoType() {
        return new TaskingInfoType();
    }

    /**
     * Create an instance of {@link ApproximableDateType }
     * 
     */
    public ApproximableDateType createApproximableDateType() {
        return new ApproximableDateType();
    }

    /**
     * Create an instance of {@link RevisionRecallType }
     * 
     */
    public RevisionRecallType createRevisionRecallType() {
        return new RevisionRecallType();
    }

    /**
     * Create an instance of {@link RecordsManagementInfoType }
     * 
     */
    public RecordsManagementInfoType createRecordsManagementInfoType() {
        return new RecordsManagementInfoType();
    }

    /**
     * Create an instance of {@link RelatedResourcesType }
     * 
     */
    public RelatedResourcesType createRelatedResourcesType() {
        return new RelatedResourcesType();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link ResourceType }
     * 
     */
    public ResourceType createResourceType() {
        return new ResourceType();
    }

    /**
     * Create an instance of {@link PlaceType }
     * 
     */
    public PlaceType createPlaceType() {
        return new PlaceType();
    }

    /**
     * Create an instance of {@link GeographicIdentifier }
     * 
     */
    public GeographicIdentifier createGeographicIdentifier() {
        return new GeographicIdentifier();
    }

    /**
     * Create an instance of {@link CompoundCountryCodeIdentifierType }
     * 
     */
    public CompoundCountryCodeIdentifierType createCompoundCountryCodeIdentifierType() {
        return new CompoundCountryCodeIdentifierType();
    }

    /**
     * Create an instance of {@link FacilityIdentifierType }
     * 
     */
    public FacilityIdentifierType createFacilityIdentifierType() {
        return new FacilityIdentifierType();
    }

    /**
     * Create an instance of {@link BoundingGeometryType }
     * 
     */
    public BoundingGeometryType createBoundingGeometryType() {
        return new BoundingGeometryType();
    }

    /**
     * Create an instance of {@link PostalAddress }
     * 
     */
    public PostalAddress createPostalAddress() {
        return new PostalAddress();
    }

    /**
     * Create an instance of {@link MetacardInfoType }
     * 
     */
    public MetacardInfoType createMetacardInfoType() {
        return new MetacardInfoType();
    }

    /**
     * Create an instance of {@link CompoundResourceIdentifierType }
     * 
     */
    public CompoundResourceIdentifierType createCompoundResourceIdentifierType() {
        return new CompoundResourceIdentifierType();
    }

    /**
     * Create an instance of {@link TitleType }
     * 
     */
    public TitleType createTitleType() {
        return new TitleType();
    }

    /**
     * Create an instance of {@link SubtitleType }
     * 
     */
    public SubtitleType createSubtitleType() {
        return new SubtitleType();
    }

    /**
     * Create an instance of {@link ContactInfoType }
     * 
     */
    public ContactInfoType createContactInfoType() {
        return new ContactInfoType();
    }

    /**
     * Create an instance of {@link CompoundSourceIdentifierType }
     * 
     */
    public CompoundSourceIdentifierType createCompoundSourceIdentifierType() {
        return new CompoundSourceIdentifierType();
    }

    /**
     * Create an instance of {@link CompoundLanguageIdentifierType }
     * 
     */
    public CompoundLanguageIdentifierType createCompoundLanguageIdentifierType() {
        return new CompoundLanguageIdentifierType();
    }

    /**
     * Create an instance of {@link DescriptionType }
     * 
     */
    public DescriptionType createDescriptionType() {
        return new DescriptionType();
    }

    /**
     * Create an instance of {@link DatesType }
     * 
     */
    public DatesType createDatesType() {
        return new DatesType();
    }

    /**
     * Create an instance of {@link RightsType }
     * 
     */
    public RightsType createRightsType() {
        return new RightsType();
    }

    /**
     * Create an instance of {@link CompoundTypeIdentifierType }
     * 
     */
    public CompoundTypeIdentifierType createCompoundTypeIdentifierType() {
        return new CompoundTypeIdentifierType();
    }

    /**
     * Create an instance of {@link FormatType }
     * 
     */
    public FormatType createFormatType() {
        return new FormatType();
    }

    /**
     * Create an instance of {@link QualifiedExtentValueType }
     * 
     */
    public QualifiedExtentValueType createQualifiedExtentValueType() {
        return new QualifiedExtentValueType();
    }

    /**
     * Create an instance of {@link SubjectType }
     * 
     */
    public SubjectType createSubjectType() {
        return new SubjectType();
    }

    /**
     * Create an instance of {@link CompoundCategoryIdentifierType }
     * 
     */
    public CompoundCategoryIdentifierType createCompoundCategoryIdentifierType() {
        return new CompoundCategoryIdentifierType();
    }

    /**
     * Create an instance of {@link CompoundKeywordIdentifierType }
     * 
     */
    public CompoundKeywordIdentifierType createCompoundKeywordIdentifierType() {
        return new CompoundKeywordIdentifierType();
    }

    /**
     * Create an instance of {@link ProductionMetricType }
     * 
     */
    public ProductionMetricType createProductionMetricType() {
        return new ProductionMetricType();
    }

    /**
     * Create an instance of {@link NonStateActorCoverageType }
     * 
     */
    public NonStateActorCoverageType createNonStateActorCoverageType() {
        return new NonStateActorCoverageType();
    }

    /**
     * Create an instance of {@link TimePeriodType }
     * 
     */
    public TimePeriodType createTimePeriodType() {
        return new TimePeriodType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link ServiceType }
     * 
     */
    public ServiceType createServiceType() {
        return new ServiceType();
    }

    /**
     * Create an instance of {@link UnknownType }
     * 
     */
    public UnknownType createUnknownType() {
        return new UnknownType();
    }

    /**
     * Create an instance of {@link ResourceManagementType }
     * 
     */
    public ResourceManagementType createResourceManagementType() {
        return new ResourceManagementType();
    }

    /**
     * Create an instance of {@link ProcessingInfoType }
     * 
     */
    public ProcessingInfoType createProcessingInfoType() {
        return new ProcessingInfoType();
    }

    /**
     * Create an instance of {@link ProducerBaseType }
     * 
     */
    public ProducerBaseType createProducerBaseType() {
        return new ProducerBaseType();
    }

    /**
     * Create an instance of {@link AffiliatedProducerType }
     * 
     */
    public AffiliatedProducerType createAffiliatedProducerType() {
        return new AffiliatedProducerType();
    }

    /**
     * Create an instance of {@link TaskingInfoType.RequesterInfo }
     * 
     */
    public TaskingInfoType.RequesterInfo createTaskingInfoTypeRequesterInfo() {
        return new TaskingInfoType.RequesterInfo();
    }

    /**
     * Create an instance of {@link TaskingInfoType.Addressee }
     * 
     */
    public TaskingInfoType.Addressee createTaskingInfoTypeAddressee() {
        return new TaskingInfoType.Addressee();
    }

    /**
     * Create an instance of {@link TaskingInfoType.TaskID }
     * 
     */
    public TaskingInfoType.TaskID createTaskingInfoTypeTaskID() {
        return new TaskingInfoType.TaskID();
    }

    /**
     * Create an instance of {@link ApproximableDateType.ApproximableDate }
     * 
     */
    public ApproximableDateType.ApproximableDate createApproximableDateTypeApproximableDate() {
        return new ApproximableDateType.ApproximableDate();
    }

    /**
     * Create an instance of {@link ApproximableDateType.SearchableDate }
     * 
     */
    public ApproximableDateType.SearchableDate createApproximableDateTypeSearchableDate() {
        return new ApproximableDateType.SearchableDate();
    }

    /**
     * Create an instance of {@link RevisionRecallType.Link }
     * 
     */
    public RevisionRecallType.Link createRevisionRecallTypeLink() {
        return new RevisionRecallType.Link();
    }

    /**
     * Create an instance of {@link RevisionRecallType.Details }
     * 
     */
    public RevisionRecallType.Details createRevisionRecallTypeDetails() {
        return new RevisionRecallType.Details();
    }

    /**
     * Create an instance of {@link RecordsManagementInfoType.RecordKeeper }
     * 
     */
    public RecordsManagementInfoType.RecordKeeper createRecordsManagementInfoTypeRecordKeeper() {
        return new RecordsManagementInfoType.RecordKeeper();
    }

    /**
     * Create an instance of {@link RecordsManagementInfoType.ApplicationSoftware }
     * 
     */
    public RecordsManagementInfoType.ApplicationSoftware createRecordsManagementInfoTypeApplicationSoftware() {
        return new RecordsManagementInfoType.ApplicationSoftware();
    }

    /**
     * Create an instance of {@link RelatedResourcesType.Link }
     * 
     */
    public RelatedResourcesType.Link createRelatedResourcesTypeLink() {
        return new RelatedResourcesType.Link();
    }

    /**
     * Create an instance of {@link OrganizationType.SubOrganization }
     * 
     */
    public OrganizationType.SubOrganization createOrganizationTypeSubOrganization() {
        return new OrganizationType.SubOrganization();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "resource")
    public JAXBElement<ResourceType> createResource(ResourceType value) {
        return new JAXBElement<ResourceType>(_Resource_QNAME, ResourceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VirtualCoverageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "virtualCoverage")
    public JAXBElement<VirtualCoverageType> createVirtualCoverage(VirtualCoverageType value) {
        return new JAXBElement<VirtualCoverageType>(_VirtualCoverage_QNAME, VirtualCoverageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PlaceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "geospatialCoverage")
    public JAXBElement<PlaceType> createGeospatialCoverage(PlaceType value) {
        return new JAXBElement<PlaceType>(_GeospatialCoverage_QNAME, PlaceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundCountryCodeIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "countryCode")
    public JAXBElement<CompoundCountryCodeIdentifierType> createCountryCode(CompoundCountryCodeIdentifierType value) {
        return new JAXBElement<CompoundCountryCodeIdentifierType>(_CountryCode_QNAME, CompoundCountryCodeIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundCountryCodeIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "subDivisionCode")
    public JAXBElement<CompoundCountryCodeIdentifierType> createSubDivisionCode(CompoundCountryCodeIdentifierType value) {
        return new JAXBElement<CompoundCountryCodeIdentifierType>(_SubDivisionCode_QNAME, CompoundCountryCodeIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FacilityIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "facilityIdentifier")
    public JAXBElement<FacilityIdentifierType> createFacilityIdentifier(FacilityIdentifierType value) {
        return new JAXBElement<FacilityIdentifierType>(_FacilityIdentifier_QNAME, FacilityIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BoundingGeometryType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "boundingGeometry")
    public JAXBElement<BoundingGeometryType> createBoundingGeometry(BoundingGeometryType value) {
        return new JAXBElement<BoundingGeometryType>(_BoundingGeometry_QNAME, BoundingGeometryType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link MetacardInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "metacardInfo")
    public JAXBElement<MetacardInfoType> createMetacardInfo(MetacardInfoType value) {
        return new JAXBElement<MetacardInfoType>(_MetacardInfo_QNAME, MetacardInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundResourceIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "identifier")
    public JAXBElement<CompoundResourceIdentifierType> createIdentifier(CompoundResourceIdentifierType value) {
        return new JAXBElement<CompoundResourceIdentifierType>(_Identifier_QNAME, CompoundResourceIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TitleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "title")
    public JAXBElement<TitleType> createTitle(TitleType value) {
        return new JAXBElement<TitleType>(_Title_QNAME, TitleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubtitleType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "subtitle")
    public JAXBElement<SubtitleType> createSubtitle(SubtitleType value) {
        return new JAXBElement<SubtitleType>(_Subtitle_QNAME, SubtitleType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "creator")
    public JAXBElement<ContactInfoType> createCreator(ContactInfoType value) {
        return new JAXBElement<ContactInfoType>(_Creator_QNAME, ContactInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "publisher")
    public JAXBElement<ContactInfoType> createPublisher(ContactInfoType value) {
        return new JAXBElement<ContactInfoType>(_Publisher_QNAME, ContactInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "contributor")
    public JAXBElement<ContactInfoType> createContributor(ContactInfoType value) {
        return new JAXBElement<ContactInfoType>(_Contributor_QNAME, ContactInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ContactInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "pointOfContact")
    public JAXBElement<ContactInfoType> createPointOfContact(ContactInfoType value) {
        return new JAXBElement<ContactInfoType>(_PointOfContact_QNAME, ContactInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundSourceIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "source")
    public JAXBElement<CompoundSourceIdentifierType> createSource(CompoundSourceIdentifierType value) {
        return new JAXBElement<CompoundSourceIdentifierType>(_Source_QNAME, CompoundSourceIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundLanguageIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "language")
    public JAXBElement<CompoundLanguageIdentifierType> createLanguage(CompoundLanguageIdentifierType value) {
        return new JAXBElement<CompoundLanguageIdentifierType>(_Language_QNAME, CompoundLanguageIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DescriptionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "description")
    public JAXBElement<DescriptionType> createDescription(DescriptionType value) {
        return new JAXBElement<DescriptionType>(_Description_QNAME, DescriptionType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "dates")
    public JAXBElement<DatesType> createDates(DatesType value) {
        return new JAXBElement<DatesType>(_Dates_QNAME, DatesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RightsType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "rights")
    public JAXBElement<RightsType> createRights(RightsType value) {
        return new JAXBElement<RightsType>(_Rights_QNAME, RightsType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundTypeIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "type")
    public JAXBElement<CompoundTypeIdentifierType> createType(CompoundTypeIdentifierType value) {
        return new JAXBElement<CompoundTypeIdentifierType>(_Type_QNAME, CompoundTypeIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FormatType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "format")
    public JAXBElement<FormatType> createFormat(FormatType value) {
        return new JAXBElement<FormatType>(_Format_QNAME, FormatType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "medium")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMedium(String value) {
        return new JAXBElement<String>(_Medium_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "mimeType")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createMimeType(String value) {
        return new JAXBElement<String>(_MimeType_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link QualifiedExtentValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "extent")
    public JAXBElement<QualifiedExtentValueType> createExtent(QualifiedExtentValueType value) {
        return new JAXBElement<QualifiedExtentValueType>(_Extent_QNAME, QualifiedExtentValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SubjectType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "subjectCoverage")
    public JAXBElement<SubjectType> createSubjectCoverage(SubjectType value) {
        return new JAXBElement<SubjectType>(_SubjectCoverage_QNAME, SubjectType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundCategoryIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "category")
    public JAXBElement<CompoundCategoryIdentifierType> createCategory(CompoundCategoryIdentifierType value) {
        return new JAXBElement<CompoundCategoryIdentifierType>(_Category_QNAME, CompoundCategoryIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CompoundKeywordIdentifierType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "keyword")
    public JAXBElement<CompoundKeywordIdentifierType> createKeyword(CompoundKeywordIdentifierType value) {
        return new JAXBElement<CompoundKeywordIdentifierType>(_Keyword_QNAME, CompoundKeywordIdentifierType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProductionMetricType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "productionMetric")
    public JAXBElement<ProductionMetricType> createProductionMetric(ProductionMetricType value) {
        return new JAXBElement<ProductionMetricType>(_ProductionMetric_QNAME, ProductionMetricType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NonStateActorCoverageType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "nonStateActor")
    public JAXBElement<NonStateActorCoverageType> createNonStateActor(NonStateActorCoverageType value) {
        return new JAXBElement<NonStateActorCoverageType>(_NonStateActor_QNAME, NonStateActorCoverageType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TimePeriodType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "temporalCoverage")
    public JAXBElement<TimePeriodType> createTemporalCoverage(TimePeriodType value) {
        return new JAXBElement<TimePeriodType>(_TemporalCoverage_QNAME, TimePeriodType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "organization")
    public JAXBElement<OrganizationType> createOrganization(OrganizationType value) {
        return new JAXBElement<OrganizationType>(_Organization_QNAME, OrganizationType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PersonType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "person")
    public JAXBElement<PersonType> createPerson(PersonType value) {
        return new JAXBElement<PersonType>(_Person_QNAME, PersonType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "service")
    public JAXBElement<ServiceType> createService(ServiceType value) {
        return new JAXBElement<ServiceType>(_Service_QNAME, ServiceType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UnknownType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "unknown")
    public JAXBElement<UnknownType> createUnknown(UnknownType value) {
        return new JAXBElement<UnknownType>(_Unknown_QNAME, UnknownType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RelatedResourcesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "relatedResource")
    public JAXBElement<RelatedResourcesType> createRelatedResource(RelatedResourcesType value) {
        return new JAXBElement<RelatedResourcesType>(_RelatedResource_QNAME, RelatedResourcesType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ResourceManagementType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "resourceManagement")
    public JAXBElement<ResourceManagementType> createResourceManagement(ResourceManagementType value) {
        return new JAXBElement<ResourceManagementType>(_ResourceManagement_QNAME, ResourceManagementType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ProcessingInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "processingInfo")
    public JAXBElement<ProcessingInfoType> createProcessingInfo(ProcessingInfoType value) {
        return new JAXBElement<ProcessingInfoType>(_ProcessingInfo_QNAME, ProcessingInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RecordsManagementInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "recordsManagementInfo")
    public JAXBElement<RecordsManagementInfoType> createRecordsManagementInfo(RecordsManagementInfoType value) {
        return new JAXBElement<RecordsManagementInfoType>(_RecordsManagementInfo_QNAME, RecordsManagementInfoType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevisionRecallType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "revisionRecall")
    public JAXBElement<RevisionRecallType> createRevisionRecall(RevisionRecallType value) {
        return new JAXBElement<RevisionRecallType>(_RevisionRecall_QNAME, RevisionRecallType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "affiliation")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createAffiliation(String value) {
        return new JAXBElement<String>(_Affiliation_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "name", scope = GeographicIdentifier.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGeographicIdentifierName(String value) {
        return new JAXBElement<String>(_GeographicIdentifierName_QNAME, String.class, GeographicIdentifier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "region", scope = GeographicIdentifier.class)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    public JAXBElement<String> createGeographicIdentifierRegion(String value) {
        return new JAXBElement<String>(_GeographicIdentifierRegion_QNAME, String.class, GeographicIdentifier.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevisionRecallType.Link }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "link", scope = RevisionRecallType.class)
    public JAXBElement<RevisionRecallType.Link> createRevisionRecallTypeLink(RevisionRecallType.Link value) {
        return new JAXBElement<RevisionRecallType.Link>(_RevisionRecallTypeLink_QNAME, RevisionRecallType.Link.class, RevisionRecallType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link RevisionRecallType.Details }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "urn:us:mil:ces:metadata:ddms:5", name = "details", scope = RevisionRecallType.class)
    public JAXBElement<RevisionRecallType.Details> createRevisionRecallTypeDetails(RevisionRecallType.Details value) {
        return new JAXBElement<RevisionRecallType.Details>(_RevisionRecallTypeDetails_QNAME, RevisionRecallType.Details.class, RevisionRecallType.class, value);
    }

}
